### ISSUE TITLE
Child class -> Node is not getting initialized when @onready

### ISSUE THREAD

**Issue by itsDrac** [itsDrac/LevelEdit#1]
Please run `p1` scene from `tmp` folder of commit [ac719f3](https://github.com/itsDrac/LevelEdit/tree/ac719f3d7769d5d3ca726f381f628c0953659d0a)

when running the scene it gives me error in c1 script line 14 saying non existing function `add_child`
![image](https://user-images.githubusercontent.com/25584851/218095514-ee5b4bcc-2ef4-40ea-b140-7dc99639b9aa.png)

the issue is when i am creating a new instance of custom `class_name Child` its onready var hbox which has a node assigned to it is should null

i tried adding this under `_ready()` function of Child class but this doesnt work 
I have tried this with signal as well

Godot version: Godot 4 beta 17.

**Comment by MikeSchulze** [comment]
you have not a node `HBoxContainer` in your scene.
The error says your variable `hbox` is null (not found)
